apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEBUG
          value: "true"

configMapGenerator:
  - name: backend-config
    namespace: smart-travel-buddy
    literals:
      - llm-model=gpt-4o
      - llm-base-url=https://api.openai.com/v1
