apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: smart-travel-buddy
spec:
  encryptedData:
    llm-api-key: AgBALrKgnpPXzWOC5RAKvl0Nwey8SE4E/dUrdQ/Ikt7doYGoSCdWH6UvvjhrcLBlZgyOSs8ycPXF9pCRFX/mE2lWH1TBc8WvBIF98cN2eVpaUQ7sT9SbvjFh+PbBr7lxKMH8bCiAIX0AtNK7fJYFTmKg5tRIwuUFsceijmUXRr+CKhSEHGC04NTJ8SKBvfXO565D4ljuXDtYgHO9JovtecAp8Q2go/Ld1aIFDy9A9nMwDXLaLeSRfNL7obXwr0XHZxuBLTs1p+iXKW2oABgj5HTqqlgty14rskFnsjGbxwry5hY+SGIt0otEnKdGSMx/ekJxe7MdjMIYcvKzITxihpPl0w+dMNSxLDA0752fSrTw8zFHHPnlMYGziRdzePXyEAtYqT+evG+scl4eYi41ERREMDpBonI5a15loBxcPVoYwRxb54Xmp82O7LWwGEoSDFt5pCWqacO23/kU2Y/nikvsUJQLOuyf7qgREfdvdcluc0+wdy5jLe0Ur7UN0jbj8tisZV/HaxZdX6gaB0kYt850gJS/p6Wkc3yF7Z4BpHfEAS5jSr20J96dddpssfn4OSugRP2nQM7tcUa1fvbz2Rjc0vC4aE2S2FhLTAMobe8toie5KBiMBKKOv8hLMLyjVnd2EZszy2iAn4byvrZjlDepwj96yrDmeL6j6poX8qSLekvVVAhBZjhi6Y9/L80RhEHe+Z8ibMYEkgk5T/SToQ==
    openweathermap: AgDCotKvr9gP+l8APJ7Kyj+zR4gpIpWIDVLMMWFkG4Tx7RtLDyGRe4O925oloERjZp2WAq4+YJyIdL62lpIDn6IiREzdvErkJRRiYW8iMnqhcJy69h2O6cJNwx/0e9mHYUqwa9GqUlNDyJm+mFWFSSGuaoUFfdUwe6uxxagAVMhKwvvnZ2oVGNbYi2WmjhbfljJitX+K1cr9Y/ftGQFJn9Mj9acPN0slZRBN2kmYm3pFym6BdXCfvRJxZp22yC6ssCUezyOU7aFpxMPLsOz+cUXKZlL3ctc3Vhll4XDDSEgdCf4F/9k6aZL5j8hQgT5ltcQPk2/rhAN7fMQOjTae/uEh/BaXhHJNnu8eWciKDqoQrfqw2MgMt8b37bDvdVNDfG5+LXLFkwUSHU28kVJKGKyu0llMfhkiryoXy+qk/rzw++vTr3QIAli2qSfEWOTDzyQUSg54BhRZSdQM6T6wEdSKeJbouRtHqE9zdrnIixrgHNSNalTugKGO4b+WlPJpIT46tCV4y9xA4AhNqdSehijpq7Qz57T6PZbtOlrvx0emgLebiZk/jsKYdgyTEzuyTGln2gx8hv6u/FOPyRKxJPYguuT+fkJn0FdidRhL0fcmTNA0v4IoRpiexBtDuL+mXYSct8kSqtraqrLMlTreXD9cnM8pULN4+BHdnjklC869J1XWPIej1s9BlpqSFT3ceQaFFEYVbZLZm+3W9tzB8OMM25lY8EKrUWMfCORLW8MrjQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: smart-travel-buddy
    type: Opaque

