apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: smart-travel-buddy
data:
  llm-model: "qwen3-14b-fp8"
  llm-base-url: "https://qwen3-14b-fp8-llm-models.apps.simpsons.lab.gfontana.me/v1"
